name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        
    services:
      ganache:
        image: trufflesuite/ganache-cli
        ports:
          - 8545:8545
        #options: >-
         # -m "describe uncle will various ankle film brother pelican apple congress animal segment"
          #-i 10

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npx -y truffle test
